# Generated by Django 2.1.7 on 2019-02-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asker', models.TextField()),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
                ('seen', models.BooleanField()),
            ],
        ),
    ]
