# Generated by Django 2.1.7 on 2019-03-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20190312_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='response',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
