# Generated by Django 2.1.7 on 2019-03-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0007_remove_question_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='response',
            field=models.TextField(blank=True, default=None),
        ),
    ]
