# Generated by Django 2.1.7 on 2019-04-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_auto_20190312_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cat',
            field=models.TextField(default='一般'),
            preserve_default=False,
        ),
    ]
