# Generated by Django 2.2.1 on 2019-05-24 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0012_auto_20190524_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.AddField(
            model_name='attachment',
            name='Project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_site.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='Project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_site.Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='Project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_site.Project'),
            preserve_default=False,
        ),
    ]
