# Generated by Django 2.2.1 on 2019-05-24 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_auto_20190524_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_site.Project'),
        ),
    ]
