# Generated by Django 2.2.1 on 2019-05-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0015_auto_20190524_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='topic',
        ),
    ]
